-- Minimal playlist view: at this stage SQLite just stores the raw TOML
-- keyed by its generated id, so the full `playlist add` circuit works
-- end to end. The rich materialized view (columns/tables for selection /
-- broadcast, to make querying and drag & drop fast) comes in a later
-- migration — deliberately not modelled here yet.
--
-- File-first reminder: the TOML file on disk is the source of truth; this
-- table is a rebuildable view. Nothing here is authoritative.
CREATE TABLE IF NOT EXISTS playlists (
    id       TEXT PRIMARY KEY,        -- UUID v4, generated by stationd
    name     TEXT NOT NULL,
    enabled  INTEGER NOT NULL DEFAULT 1,
    toml     TEXT NOT NULL,           -- raw canonical TOML (source of truth)
    added_at TEXT NOT NULL DEFAULT (datetime('now'))
);
