use std::path::PathBuf;
use std::sync::Arc;
use std::time::Instant;

use sqlx::SqlitePool;
use tokio::sync::{oneshot, Mutex};
use tonic::{Request, Response, Status as TonicStatus};

// Code generated by tonic-build from proto/station.proto (see build.rs).
pub mod station {
    tonic::include_proto!("station");
}

use station::station_server::Station;
use station::{
    PlaylistAddReply, PlaylistAddRequest, PlaylistListReply, PlaylistListRequest, PlaylistSummary,
    PlaylistSyncError, PlaylistSyncReply, PlaylistSyncRequest, QuitReply, QuitRequest, StatusReply,
    StatusRequest,
};

use crate::playlist::{self, Playlist};
use crate::store;

/// Implementation of the `Station` gRPC service.
///
/// Knows nothing about Liquidsoap/Icecast or SQLite — deliberately staying
/// on the strict minimum needed for `stationctl status` / `quit` to work.
/// Future RPCs (playlists, roles...) will grow this same service over time,
/// starting in proto/station.proto.
pub struct StationService {
    station_name: String,
    started_at: Instant,
    db: SqlitePool,
    playlist_root: PathBuf,
    // A `oneshot::Sender` only fires once. The `Mutex<Option<_>>` lets us
    // "consume" it (`.take()`) on the first `quit` received without
    // panicking if a misbehaving client calls `quit` twice.
    shutdown: Arc<Mutex<Option<oneshot::Sender<()>>>>,
}

impl StationService {
    pub fn new(
        station_name: String,
        db: SqlitePool,
        playlist_root: PathBuf,
        shutdown: oneshot::Sender<()>,
    ) -> Self {
        Self {
            station_name,
            started_at: Instant::now(),
            db,
            playlist_root,
            shutdown: Arc::new(Mutex::new(Some(shutdown))),
        }
    }

    /// Upsert one already-parsed playlist into the SQLite view. Thin
    /// wrapper over `store::upsert` (the metier lives there so it can be
    /// tested without a gRPC server). stationd is the single writer.
    async fn upsert_view(
        &self,
        id: &str,
        playlist: &Playlist,
        rewritten: &str,
        rel_path: Option<&str>,
    ) -> Result<(), String> {
        store::upsert(&self.db, id, playlist, rewritten, rel_path)
            .await
            .map_err(|e| format!("could not update playlist view: {e}"))
    }
}

#[tonic::async_trait]
impl Station for StationService {
    async fn status(
        &self,
        _request: Request<StatusRequest>,
    ) -> Result<Response<StatusReply>, TonicStatus> {
        let reply = StatusReply {
            station_name: self.station_name.clone(),
            uptime_seconds: self.started_at.elapsed().as_secs(),
            pid: std::process::id(),
        };
        Ok(Response::new(reply))
    }

    async fn quit(
        &self,
        _request: Request<QuitRequest>,
    ) -> Result<Response<QuitReply>, TonicStatus> {
        // Reply to the client BEFORE tearing down the server: otherwise it
        // never receives the acknowledgement (the connection drops with the
        // process).
        if let Some(tx) = self.shutdown.lock().await.take() {
            let _ = tx.send(());
        }
        Ok(Response::new(QuitReply {}))
    }

    async fn playlist_add(
        &self,
        request: Request<PlaylistAddRequest>,
    ) -> Result<Response<PlaylistAddReply>, TonicStatus> {
        let toml_content = request.into_inner().toml_content;

        // Per-file metier: parse (strict) + validate (business rules).
        // Cross-playlist checks (refs/cycles) are NOT done here — a single
        // file cannot see the whole set; that is `sync`'s job.
        let playlist = Playlist::parse(&toml_content)
            .map_err(|e| TonicStatus::invalid_argument(e.to_string()))?;
        playlist
            .validate()
            .map_err(|e| TonicStatus::invalid_argument(e.to_string()))?;

        let (rewritten, id) = playlist::assign_id(&toml_content)
            .map_err(|e| TonicStatus::invalid_argument(e.to_string()))?;

        // A file brought in from outside has no position in the tree → no
        // rel_path. A later `sync` will set it if the file lives under the
        // root.
        self.upsert_view(&id.to_string(), &playlist, &rewritten, None)
            .await
            .map_err(TonicStatus::internal)?;

        Ok(Response::new(PlaylistAddReply {
            toml_content: rewritten,
            id: id.to_string(),
        }))
    }

    async fn playlist_sync(
        &self,
        _request: Request<PlaylistSyncRequest>,
    ) -> Result<Response<PlaylistSyncReply>, TonicStatus> {
        // The whole reconciliation (walk the root, per-file load+validate,
        // whole-set validate, persist survivors, write ids back) lives in
        // `sync::sync_root` — a plain function with no tonic dependency, so
        // it can be driven directly by an integration test. This handler is
        // a thin translator: run it, map the metier errors to the proto.
        let outcome = crate::sync::sync_root(&self.db, &self.playlist_root).await;

        let errors = outcome
            .errors
            .into_iter()
            .map(|e| PlaylistSyncError {
                path: e.path,
                message: e.message,
            })
            .collect();

        Ok(Response::new(PlaylistSyncReply {
            added: outcome.added,
            errors,
        }))
    }

    async fn playlist_list(
        &self,
        _request: Request<PlaylistListRequest>,
    ) -> Result<Response<PlaylistListReply>, TonicStatus> {
        // Read from the view via `store::list`; the handler only maps the
        // metier rows to the proto message.
        let rows = store::list(&self.db)
            .await
            .map_err(|e| TonicStatus::internal(format!("could not read playlist view: {e}")))?;

        let playlists = rows
            .into_iter()
            .map(|r| PlaylistSummary {
                id: r.id,
                rel_path: r.rel_path.unwrap_or_default(),
                name: r.name,
                mode: r.mode,
                enabled: r.enabled,
            })
            .collect();

        Ok(Response::new(PlaylistListReply { playlists }))
    }
}
