use std::sync::Arc;
use std::time::Instant;

use tokio::sync::{oneshot, Mutex};
use tonic::{Request, Response, Status as TonicStatus};

// Code generated by tonic-build from proto/station.proto (see build.rs).
pub mod station {
    tonic::include_proto!("station");
}

use station::station_server::Station;
use station::{QuitReply, QuitRequest, StatusReply, StatusRequest};

/// Implementation of the `Station` gRPC service.
///
/// Knows nothing about Liquidsoap/Icecast or SQLite — deliberately staying
/// on the strict minimum needed for `stationctl status` / `quit` to work.
/// Future RPCs (playlists, roles...) will grow this same service over time,
/// starting in proto/station.proto.
pub struct StationService {
    station_name: String,
    started_at: Instant,
    // A `oneshot::Sender` only fires once. The `Mutex<Option<_>>` lets us
    // "consume" it (`.take()`) on the first `quit` received without
    // panicking if a misbehaving client calls `quit` twice.
    shutdown: Arc<Mutex<Option<oneshot::Sender<()>>>>,
}

impl StationService {
    pub fn new(station_name: String, shutdown: oneshot::Sender<()>) -> Self {
        Self {
            station_name,
            started_at: Instant::now(),
            shutdown: Arc::new(Mutex::new(Some(shutdown))),
        }
    }
}

#[tonic::async_trait]
impl Station for StationService {
    async fn status(
        &self,
        _request: Request<StatusRequest>,
    ) -> Result<Response<StatusReply>, TonicStatus> {
        let reply = StatusReply {
            station_name: self.station_name.clone(),
            uptime_seconds: self.started_at.elapsed().as_secs(),
            pid: std::process::id(),
        };
        Ok(Response::new(reply))
    }

    async fn quit(
        &self,
        _request: Request<QuitRequest>,
    ) -> Result<Response<QuitReply>, TonicStatus> {
        // Reply to the client BEFORE tearing down the server: otherwise it
        // never receives the acknowledgement (the connection drops with the
        // process).
        if let Some(tx) = self.shutdown.lock().await.take() {
            let _ = tx.send(());
        }
        Ok(Response::new(QuitReply {}))
    }
}
