//! Icecast config generator — `[icecast.server]` → `icecast.xml` (pure).
//!
//! Same model as `ls_script`: stationd **writes** Icecast's config at
//! start-up (only when it changed) and never launches Icecast, which runs
//! under its own unit (`icecast2 -c <config_path>`): restarting stationd
//! never cuts the stream; a changed config needs an Icecast restart.
//!
//! What stationd owns, from `stationd.toml`:
//! - one `<mount>` per `[[liquidsoap.output]]`, with **that output's source
//!   password** (Liquidsoap and Icecast cannot disagree) and
//!   `<charset>UTF-8</charset>` (titles are sent in UTF-8);
//! - `<sources>` = the number of outputs: nobody else can feed this Icecast;
//! - admin credentials = `[icecast]` (the ones the sampler reads with);
//! - reverse proxies trusted for `X-Forwarded-For` (Icecast 2.5): one
//!   virtual listen socket per address, referenced by the public socket.
//!
//! **No global `<source-password>`**: only the declared mounts can be fed,
//! each with its own password. Checked against a real Icecast (2.4.4): with
//! a global password, anyone holding it could create any other mount; without
//! it, an undeclared mount is refused (401) whatever the password.

use std::path::Path;

use crate::config::{IcecastConfig, IcecastServerConfig, LiquidsoapConfig};

/// Escape for XML text and attribute values.
fn esc(s: &str) -> String {
    let mut o = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => o.push_str("&amp;"),
            '<' => o.push_str("&lt;"),
            '>' => o.push_str("&gt;"),
            '"' => o.push_str("&quot;"),
            '\'' => o.push_str("&apos;"),
            c => o.push(c),
        }
    }
    o
}

fn path(p: &Path) -> String {
    esc(&p.to_string_lossy())
}

/// Render the whole `icecast.xml`. `ic` must carry a validated `server`.
pub fn render(ic: &IcecastConfig, srv: &IcecastServerConfig, ls: &LiquidsoapConfig, station_name: &str) -> String {
    let mut o = String::new();
    o.push_str("<?xml version=\"1.0\"?>\n");
    o.push_str(&format!(
        "<!-- Generated by stationd {} from [icecast] / [icecast.server] /\n     \
         [[liquidsoap.output]] in stationd.toml. Rewritten at stationd start-up\n     \
         when it changes: restart Icecast to apply. Do not edit by hand. -->\n",
        env!("CARGO_PKG_VERSION")
    ));
    o.push_str("<icecast>\n");
    // <location> = the station name (the only name in the config). <hostname>
    // stays Icecast's default: public listen URLs belong to the reverse proxy.
    o.push_str(&format!("    <location>{}</location>\n", esc(station_name)));
    o.push_str(&format!("    <admin>{}</admin>\n", esc(&srv.admin_email)));
    o.push_str("    <hostname>localhost</hostname>\n");

    o.push_str("    <limits>\n");
    o.push_str(&format!("        <clients>{}</clients>\n", srv.max_clients));
    o.push_str(&format!("        <sources>{}</sources>\n", ls.outputs.len()));
    o.push_str(
        "        <queue-size>524288</queue-size>\n\
         \x20       <client-timeout>30</client-timeout>\n\
         \x20       <header-timeout>15</header-timeout>\n\
         \x20       <source-timeout>10</source-timeout>\n\
         \x20       <burst-size>65535</burst-size>\n",
    );
    o.push_str("    </limits>\n");

    o.push_str("    <authentication>\n");
    o.push_str(&format!("        <admin-user>{}</admin-user>\n", esc(&ic.admin_user)));
    o.push_str(&format!("        <admin-password>{}</admin-password>\n", esc(&ic.admin_password)));
    o.push_str("    </authentication>\n");

    o.push_str("    <listen-socket id=\"public\">\n");
    o.push_str(&format!("        <port>{}</port>\n", srv.port));
    if let Some(b) = &srv.bind_address {
        o.push_str(&format!("        <bind-address>{}</bind-address>\n", esc(b)));
    }
    for i in 1..=srv.trusted_proxies.len() {
        o.push_str(&format!("        <trusted-proxy>#proxy-{i}</trusted-proxy>\n"));
    }
    o.push_str("    </listen-socket>\n");
    for (i, p) in srv.trusted_proxies.iter().enumerate() {
        o.push_str(&format!(
            "    <listen-socket id=\"proxy-{}\" type=\"virtual\">\n        <client-address>{}</client-address>\n    </listen-socket>\n",
            i + 1,
            esc(p)
        ));
    }

    // CORS for web players (as in Icecast 2.5's shipped config).
    o.push_str(
        "    <http-headers>\n\
         \x20       <header type=\"cors\" name=\"Access-Control-Allow-Origin\" />\n\
         \x20       <header type=\"cors\" name=\"Access-Control-Allow-Headers\" />\n\
         \x20       <header type=\"cors\" name=\"Access-Control-Expose-Headers\" />\n\
         \x20   </http-headers>\n",
    );

    for out in &ls.outputs {
        o.push_str("    <mount type=\"normal\">\n");
        o.push_str(&format!("        <mount-name>{}</mount-name>\n", esc(&out.mount)));
        o.push_str(&format!("        <password>{}</password>\n", esc(&out.password)));
        o.push_str("        <charset>UTF-8</charset>\n");
        o.push_str("    </mount>\n");
    }

    o.push_str("    <paths>\n");
    o.push_str(&format!("        <basedir>{}</basedir>\n", path(&srv.share_dir)));
    o.push_str(&format!("        <logdir>{}</logdir>\n", path(&srv.log_dir)));
    o.push_str(&format!("        <webroot>{}</webroot>\n", path(&srv.share_dir.join("web"))));
    o.push_str(&format!("        <adminroot>{}</adminroot>\n", path(&srv.share_dir.join("admin"))));
    o.push_str(&format!("        <reportxmldb>{}</reportxmldb>\n", path(&srv.share_dir.join("report-db.xml"))));
    o.push_str("        <alias source=\"/\" destination=\"/status.xsl\"/>\n");
    o.push_str("    </paths>\n");

    o.push_str(
        "    <logging>\n\
         \x20       <accesslog>access.log</accesslog>\n\
         \x20       <errorlog>error.log</errorlog>\n\
         \x20       <loglevel>information</loglevel>\n\
         \x20       <logsize>10000</logsize>\n\
         \x20   </logging>\n\
         \x20   <security>\n\
         \x20       <chroot>false</chroot>\n\
         \x20   </security>\n",
    );
    o.push_str("</icecast>\n");
    o
}

/// Write the config only when its content changed (atomic: temp + rename),
/// mode 0640 on Unix — it holds the passwords; Icecast's user must be in the
/// file's group (see [`set_group`] / [`access`]). Returns `true` when
/// (re)written.
pub fn write_if_changed(path: &Path, xml: &str) -> std::io::Result<bool> {
    if let Ok(current) = std::fs::read_to_string(path) {
        if current == xml {
            return Ok(false);
        }
    }
    if let Some(dir) = path.parent().filter(|d| !d.as_os_str().is_empty()) {
        std::fs::create_dir_all(dir)?;
    }
    let tmp = path.with_extension("xml.tmp");
    {
        use std::io::Write;
        let mut opts = std::fs::OpenOptions::new();
        opts.write(true).create(true).truncate(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            opts.mode(0o640);
        }
        let mut f = opts.open(&tmp)?;
        f.write_all(xml.as_bytes())?;
        f.sync_all()?;
    }
    #[cfg(unix)]
    {
        // `mode` only applies at creation: a leftover temp keeps its mode.
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&tmp, std::fs::Permissions::from_mode(0o640))?;
    }
    std::fs::rename(&tmp, path)?;
    Ok(true)
}

/// Give the file to `group` (by name), keeping its owner. Checked at every
/// start (the group may change without the content changing). Loud errors:
/// unknown group, or stationd not a member of it.
#[cfg(unix)]
pub fn set_group(path: &Path, group: &str) -> Result<(), String> {
    let gid = gid_of(group)?.ok_or_else(|| {
        format!("group {group:?} does not exist (create it at install: groupadd --system {group})")
    })?;
    std::os::unix::fs::chown(path, None, Some(gid)).map_err(|e| {
        if e.kind() == std::io::ErrorKind::PermissionDenied {
            format!(
                "cannot give {} to group {group:?}: the user running stationd is not a member \
                 (usermod -aG {group} <user>, then log in again / restart the unit)",
                path.display()
            )
        } else {
            format!("chgrp {group} {}: {e}", path.display())
        }
    })
}

#[cfg(not(unix))]
pub fn set_group(_path: &Path, group: &str) -> Result<(), String> {
    Err(format!("file_group {group:?}: Unix only"))
}

/// `0640, group stationd` — what the file really is, for the start-up log
/// and `stationctl icecast render` (nothing guessed).
#[cfg(unix)]
pub fn access(path: &Path) -> Result<String, String> {
    use std::os::unix::fs::{MetadataExt, PermissionsExt};
    let m = std::fs::metadata(path).map_err(|e| format!("{}: {e}", path.display()))?;
    let group = group_name(m.gid())?.unwrap_or_else(|| m.gid().to_string());
    Ok(format!("{:04o}, group {group}", m.permissions().mode() & 0o7777))
}

#[cfg(not(unix))]
pub fn access(_path: &Path) -> Result<String, String> {
    Ok(String::from("(permissions not reported on this OS)"))
}

/// Group id of `name` (`None` = no such group).
#[cfg(unix)]
fn gid_of(name: &str) -> Result<Option<u32>, String> {
    let cname = std::ffi::CString::new(name).map_err(|_| format!("group {name:?}: NUL byte"))?;
    let mut buf = vec![0 as libc::c_char; 16 * 1024];
    let mut grp: libc::group = unsafe { std::mem::zeroed() };
    let mut out: *mut libc::group = std::ptr::null_mut();
    // SAFETY: every pointer refers to a live local of the right type/size.
    let rc = unsafe { libc::getgrnam_r(cname.as_ptr(), &mut grp, buf.as_mut_ptr(), buf.len(), &mut out) };
    if rc != 0 {
        return Err(format!("group {name:?}: lookup failed (errno {rc})"));
    }
    Ok((!out.is_null()).then_some(grp.gr_gid))
}

/// Name of group `gid` (`None` = no name).
#[cfg(unix)]
fn group_name(gid: u32) -> Result<Option<String>, String> {
    let mut buf = vec![0 as libc::c_char; 16 * 1024];
    let mut grp: libc::group = unsafe { std::mem::zeroed() };
    let mut out: *mut libc::group = std::ptr::null_mut();
    // SAFETY: every pointer refers to a live local of the right type/size.
    let rc = unsafe { libc::getgrgid_r(gid, &mut grp, buf.as_mut_ptr(), buf.len(), &mut out) };
    if rc != 0 {
        return Err(format!("gid {gid}: lookup failed (errno {rc})"));
    }
    if out.is_null() {
        return Ok(None);
    }
    // SAFETY: gr_name is a NUL-terminated string inside `buf`, alive here.
    let name = unsafe { std::ffi::CStr::from_ptr(grp.gr_name) };
    Ok(Some(name.to_string_lossy().into_owned()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;

    const CFG: &str = r#"
        [station]
        name = "Ma Radio & Co"
        timezone = "Europe/Paris"
        [server]
        grpc_bind = "127.0.0.1:50051"
        [database]
        path = "./d.db"
        [media]
        library_path = "./media"
        [playlist]
        path = "./playlist"
        [liquidsoap]
        script_path = "./data/station.liq"
        api_token = "t"
        fallback_path = "/srv/error.mp3"
        halted_path = "/srv/noise.mp3"
        [[liquidsoap.output]]
        host = "127.0.0.1"
        port = 8000
        password = "src<1>"
        mount = "/radio.mp3"
        [[liquidsoap.output]]
        host = "127.0.0.1"
        port = 8000
        password = "src2"
        mount = "/radio-lo.mp3"
        bitrate = 64
        [icecast]
        admin_url = "http://127.0.0.1:8000"
        admin_password = "adm&n"
        [icecast.server]
        trusted_proxies = ["192.168.1.94", "10.0.0.2"]
    "#;

    fn render_cfg(extra: &str) -> String {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("c.toml");
        std::fs::write(&p, format!("{CFG}{extra}")).unwrap();
        let c = Config::load(&p).unwrap();
        let ic = c.icecast.as_ref().unwrap();
        render(ic, ic.server.as_ref().unwrap(), c.liquidsoap.as_ref().unwrap(), &c.station.name)
    }

    /// The generated file is well-formed XML and says what the config says.
    #[test]
    fn renders_valid_xml_with_our_mounts_and_credentials() {
        let xml = render_cfg("");
        let doc = roxmltree::Document::parse(&xml).expect("well-formed XML");
        let root = doc.root_element();
        assert_eq!(root.tag_name().name(), "icecast");
        let text = |path: &[&str]| -> Vec<String> {
            let mut nodes = vec![root];
            for name in path {
                nodes = nodes
                    .iter()
                    .flat_map(|n| n.children().filter(|c| c.has_tag_name(*name)))
                    .collect();
            }
            nodes.iter().map(|n| n.text().unwrap_or("").to_string()).collect()
        };
        assert_eq!(text(&["location"]), ["Ma Radio & Co"], "escaped station name");
        assert_eq!(text(&["hostname"]), ["localhost"], "public URLs: the reverse proxy");
        assert_eq!(text(&["limits", "sources"]), ["2"], "only our outputs can feed it");
        assert_eq!(text(&["authentication", "admin-password"]), ["adm&n"]);
        assert!(text(&["authentication", "source-password"]).is_empty(), "no global: only our mounts");
        assert_eq!(text(&["mount", "mount-name"]), ["/radio.mp3", "/radio-lo.mp3"]);
        assert_eq!(text(&["mount", "password"]), ["src<1>", "src2"], "each output's own");
        assert_eq!(text(&["mount", "charset"]), ["UTF-8", "UTF-8"]);
        assert_eq!(text(&["paths", "webroot"]), ["/usr/share/icecast2/web"]);
    }

    #[test]
    fn one_virtual_socket_per_trusted_proxy() {
        let xml = render_cfg("");
        let doc = roxmltree::Document::parse(&xml).unwrap();
        let sockets: Vec<_> = doc.root_element().children().filter(|n| n.has_tag_name("listen-socket")).collect();
        assert_eq!(sockets.len(), 3);
        let public = sockets[0];
        assert_eq!(public.attribute("id"), Some("public"));
        let refs: Vec<_> = public
            .children()
            .filter(|n| n.has_tag_name("trusted-proxy"))
            .map(|n| n.text().unwrap())
            .collect();
        assert_eq!(refs, ["#proxy-1", "#proxy-2"]);
        for (sock, ip) in sockets[1..].iter().zip(["192.168.1.94", "10.0.0.2"]) {
            assert_eq!(sock.attribute("type"), Some("virtual"));
            let id = format!("#{}", sock.attribute("id").unwrap());
            assert!(refs.contains(&id.as_str()));
            let addr = sock.children().find(|n| n.has_tag_name("client-address")).unwrap();
            assert_eq!(addr.text(), Some(ip));
        }
    }

    #[test]
    fn no_proxy_no_virtual_socket_and_optional_bind() {
        let xml = render_cfg("");
        assert!(!render_cfg_no_proxy().contains("trusted-proxy"));
        assert!(!xml.contains("bind-address"));
        let bound = render_cfg("        bind_address = \"127.0.0.1\"\n");
        assert!(bound.contains("<bind-address>127.0.0.1</bind-address>"));
    }

    fn render_cfg_no_proxy() -> String {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("c.toml");
        std::fs::write(&p, CFG.replace("trusted_proxies = [\"192.168.1.94\", \"10.0.0.2\"]", "")).unwrap();
        let c = Config::load(&p).unwrap();
        let ic = c.icecast.as_ref().unwrap();
        render(ic, ic.server.as_ref().unwrap(), c.liquidsoap.as_ref().unwrap(), &c.station.name)
    }

    #[cfg(unix)]
    #[test]
    fn group_is_set_and_reported_or_refused_loudly() {
        use std::os::unix::fs::MetadataExt;
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("icecast.xml");
        write_if_changed(&p, "<icecast/>").unwrap();
        // Our own group: always allowed.
        let own = group_name(std::fs::metadata(&p).unwrap().gid()).unwrap().expect("named group");
        set_group(&p, &own).unwrap();
        assert_eq!(access(&p).unwrap(), format!("0640, group {own}"));
        let e = set_group(&p, "no-such-group-stationd-test").unwrap_err();
        assert!(e.contains("does not exist") && e.contains("groupadd"), "{e}");
    }

    #[test]
    fn write_is_atomic_private_and_only_on_change() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("sub/icecast.xml");
        assert!(write_if_changed(&p, "<icecast/>").unwrap());
        assert!(!write_if_changed(&p, "<icecast/>").unwrap(), "unchanged → not rewritten");
        assert!(write_if_changed(&p, "<icecast></icecast>").unwrap());
        assert_eq!(std::fs::read_to_string(&p).unwrap(), "<icecast></icecast>");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&p).unwrap().permissions().mode() & 0o777;
            assert_eq!(mode, 0o640, "holds passwords");
        }
    }
}
