//! Liquidsoap script generator (pure: config in, `.liq` text out).
//!
//! In this architecture Liquidsoap decides NOTHING: the grid, the playlists,
//! the overrides and the broadcast gate all live in stationd. The generated
//! script is only an air chain plus the bridge back to stationd:
//!
//! ```text
//! pull   = request.dynamic(POST /ls/v1/next)   # stationd resolves every track
//! pull   = cross(pull)                         # optional crossfade
//! radio  = fallback(track_sensitive=false, [
//!            pull,
//!            halted noise   (while stationd reports paused/stopped),
//!            blank          (until stationd answered once — start-up),
//!            safety fallback (nothing to air / stationd unreachable) ])
//! radio  → normalize/compress (optional) → custom include → icecast outputs
//! on_track(pull | halted noise | fallback) → POST /ls/v1/track  # what REALLY airs
//! ```
//!
//! Halted ≠ fallback: when the station is paused/stopped stationd answers
//! `halted`, and the background noise fills the air — never the safety file.
//! The current track is never cut: the pull source stays first while it still
//! has a track; the noise only takes over at its end.
//!
//! Track starts are observed on each source BEFORE the air-chain operators
//! (the pull, the noise, the fallback): a track that enters through a
//! crossfade does not raise `on_track` downstream of `cross` (seen on a real
//! Liquidsoap), while the pull source always does — when it starts being
//! read, i.e. at the start of the transition.
//!
//! Every user-provided string is emitted through [`liq_string`], which also
//! neutralises Liquidsoap's `#{…}` interpolation.

use std::path::Path;

use crate::config::{CrossfadeMode, IcecastOutput, LiquidsoapConfig, OutputFormat};

/// Header name Liquidsoap sends the shared token in (lower-case: HTTP header
/// names are case-insensitive, axum normalises them).
pub const TOKEN_HEADER: &str = "x-stationd-token";

/// Retry delay of the pull source when stationd returns nothing (halted,
/// fallback): also the polling period while halted, i.e. the resume latency.
const PULL_RETRY_S: f64 = 2.0;
/// HTTP timeout of a bridge call, seconds.
const HTTP_TIMEOUT_S: f64 = 5.0;
/// Timeout for preparing one request (file resolution), seconds.
const REQUEST_TIMEOUT_S: f64 = 20.0;

/// A Liquidsoap string literal. Escapes `\` and `"`, turns control chars into
/// escapes, and splits every `#{` so Liquidsoap never interpolates it:
/// `a#{b` → `("a#" ^ "{b")`.
pub fn liq_string(s: &str) -> String {
    let mut esc = String::with_capacity(s.len() + 2);
    for c in s.chars() {
        match c {
            '\\' => esc.push_str("\\\\"),
            '"' => esc.push_str("\\\""),
            '\n' => esc.push_str("\\n"),
            '\r' => esc.push_str("\\r"),
            '\t' => esc.push_str("\\t"),
            c => esc.push(c),
        }
    }
    if esc.contains("#{") {
        format!("(\"{}\")", esc.replace("#{", "#\" ^ \"{"))
    } else {
        format!("\"{esc}\"")
    }
}

/// A float literal Liquidsoap accepts (always with a decimal point).
fn liq_float(x: f64) -> String {
    let s = format!("{x}");
    if s.contains('.') || s.contains('e') {
        s
    } else {
        format!("{s}.")
    }
}

/// Liquidsoap does not share stationd's working directory: every path handed
/// to it is made absolute (against stationd's CWD, like the rest of the
/// config). Falls back to the path as given if the CWD is unreadable.
fn absolute(p: &Path) -> std::path::PathBuf {
    std::path::absolute(p).unwrap_or_else(|_| p.to_path_buf())
}

fn liq_path(p: &Path) -> String {
    liq_string(&p.to_string_lossy())
}

/// Render the whole script. `station_name` is the default Icecast stream name.
pub fn render(ls: &LiquidsoapConfig, station_name: &str) -> String {
    let mut o = String::new();
    let api_url = format!("http://{}/ls/v1", ls.http_bind);

    o.push_str(&format!(
        "# ─────────────────────────────────────────────────────────────────────\n\
         # GENERATED BY stationd {} — DO NOT EDIT.\n\
         # Rewritten at stationd start-up from [liquidsoap] in stationd.toml;\n\
         # restart Liquidsoap to pick up a change. Customise through\n\
         # [liquidsoap] custom_include (it sees and may reassign `radio`).\n\
         # Station: {}\n\
         # ─────────────────────────────────────────────────────────────────────\n\n",
        env!("CARGO_PKG_VERSION"),
        station_name.replace('\n', " ")
    ));

    o.push_str(&format!(
        "log.stdout := true\n\
         log.file := false\n\
         log.level := {}\n\
         settings.encoder.metadata.export := [\"artist\", \"title\", \"album\", \"song\"]\n\n",
        ls.log_level
    ));

    // ── bridge ────────────────────────────────────────────────────────────
    o.push_str(&format!(
        r##"# ─── stationd bridge ──────────────────────────────────────────────────
stationd = ()
let stationd.api_url = {api_url}
let stationd.api_token = {token}
# True while stationd reports the station paused/stopped.
let stationd.halted = ref(false)
# True until stationd answered once (start-up: silence, not the fallback file).
let stationd.loading = ref(true)
# Last reply kind, to log transitions only (the pull polls while idle).
let stationd.last_kind = ref("")
# After an empty reply (halted, nothing to air, stationd unreachable), no new
# call before this instant: the air chain may re-poll the pull many times per
# second around a track end (seen on a real Liquidsoap). Bounds the polling to
# one call per retry delay — also the resume latency.
let stationd.next_not_before = ref(0.)

def stationd.post(endpoint, payload) =
  try
    r = http.post(
      stationd.api_url ^ "/" ^ endpoint,
      headers=[
        ("Content-Type", "application/json"),
        ("User-Agent", "Liquidsoap stationd"),
        ("X-Stationd-Token", stationd.api_token)
      ],
      timeout={http_timeout},
      data=payload
    )
    if r.status_code == 200 then
      "#{{r}}"
    else
      log.important(label="stationd", "#{{endpoint}}: HTTP #{{r.status_code}}")
      null
    end
  catch err do
    log.severe(label="stationd", "#{{endpoint}}: #{{error.kind(err)}}: #{{error.message(err)}}")
    null
  end
end

def stationd.transition_log(kind, detail) =
  if stationd.last_kind() != kind then
    log.important(label="stationd", "next: #{{kind}} #{{detail}}")
    stationd.last_kind := kind
  end
end

# Pull: stationd resolves the next track (grid, overrides, broadcast gate).
def stationd.fetch_next() =
  resp = stationd.post("next", "{{}}")
  stationd.loading := false
  if null.defined(resp) then
    try
      let json.parse ({{kind, uri, state, reason}} : {{
        kind: string, uri: string, state: string, reason: string
      }}) = null.get(resp)
      if kind == "file" then
        stationd.halted := false
        stationd.transition_log(kind, "")
        request.create(uri)
      elsif kind == "halted" then
        stationd.halted := true
        stationd.transition_log(kind, "(#{{state}}): halted noise at the end of the current track")
        null
      else
        stationd.halted := false
        stationd.transition_log(kind, "(#{{reason}}): safety fallback")
        null
      end
    catch err do
      log.severe(label="stationd", "next: bad reply: #{{error.kind(err)}}: #{{error.message(err)}}")
      null
    end
  else
    null
  end
end

def stationd.next() =
  if time() < stationd.next_not_before() then
    null
  else
    r = stationd.fetch_next()
    if not null.defined(r) then
      stationd.next_not_before := time() + {retry}
    end
    r
  end
end

# Report what REALLY starts airing: one of our tracks (rid) or one of
# Liquidsoap's own sources (kind = halted | fallback).
def stationd.report(rid, kind) =
  j = json()
  j.add("rid", rid)
  j.add("kind", kind)
  ignore(stationd.post("track", json.stringify(compact=true, j)))
end

"##,
        api_url = liq_string(&api_url),
        token = liq_string(&ls.api_token),
        http_timeout = liq_float(HTTP_TIMEOUT_S),
        retry = liq_float(PULL_RETRY_S),
    ));

    // ── sources ───────────────────────────────────────────────────────────
    o.push_str(&format!(
        "# ─── air chain ─────────────────────────────────────────────────────────\n\
         pull = request.dynamic(id=\"stationd_pull\", retry_delay={retry}, timeout={rto}, stationd.next)\n\
         source.methods(pull).on_track(synchronous=false, fun (m) -> stationd.report(m[\"stationd_rid\"], \"\"))\n",
        retry = liq_float(PULL_RETRY_S),
        rto = liq_float(REQUEST_TIMEOUT_S),
    ));

    match ls.crossfade.mode {
        CrossfadeMode::None => o.push_str("# crossfade: none (hard cut)\n"),
        CrossfadeMode::Simple => o.push_str(&format!(
            "def stationd.transition(a, b) =\n  \
               cross.simple(a.source, b.source, fade_in={fade}, fade_out={fade})\n\
             end\n\
             pull = cross(id=\"stationd_cross\", duration={dur}, stationd.transition, pull)\n",
            fade = liq_float(ls.crossfade.fade),
            dur = liq_float(ls.crossfade.duration),
        )),
    }

    o.push_str(&format!(
        "\n# Liquidsoap's own sources. Plain `single` on a local file (no annotate:)\n\
         # stays infallible.\n\
         halted_noise = single(id=\"stationd_halted\", {halted})\n\
         source.methods(halted_noise).on_track(synchronous=false, fun (_) -> stationd.report(\"\", \"halted\"))\n\
         safety = single(id=\"stationd_fallback\", {fallback})\n\
         source.methods(safety).on_track(synchronous=false, fun (_) -> stationd.report(\"\", \"fallback\"))\n\
         startup = blank(id=\"stationd_startup\")\n\n\
         radio = fallback(\n  \
           id=\"stationd_air\",\n  \
           track_sensitive=false,\n  \
           [\n    \
             pull,\n    \
             source.available(halted_noise, {{stationd.halted()}}),\n    \
             source.available(startup, {{stationd.loading()}}),\n    \
             safety\n  \
           ]\n\
         )\n",
        halted = liq_path(&absolute(&ls.halted_path)),
        fallback = liq_path(&absolute(&ls.fallback_path)),
    ));

    if ls.normalize {
        o.push_str(
            "\n# Normalisation + compression\n\
             radio = normalize(target=0., window=0.03, gain_min=-16., gain_max=0., radio)\n\
             radio = compress.exponential(radio, mu=1.0)\n",
        );
    }


    if let Some(inc) = &ls.custom_include {
        o.push_str(&format!(
            "\n# ─── custom include ([liquidsoap] custom_include) ──────────────────────\n\
             %include \"{}\"\n",
            absolute(inc).to_string_lossy()
        ));
    }

    o.push_str("\n# ─── outputs ───────────────────────────────────────────────────────────\n");
    for (i, out) in ls.outputs.iter().enumerate() {
        o.push_str(&render_output(i + 1, out, station_name));
    }
    o
}

fn render_output(n: usize, out: &IcecastOutput, station_name: &str) -> String {
    let encoder = match out.format {
        OutputFormat::Mp3 => format!(
            "%ffmpeg(format=\"mp3\", %audio(codec=\"libmp3lame\", ac=2, ar=44100, b=\"{}k\"))",
            out.bitrate
        ),
    };
    let name = out.name.as_deref().unwrap_or(station_name);
    format!(
        "output.icecast(\n  \
           {encoder},\n  \
           id=\"stationd_out_{n}\",\n  \
           host={host},\n  \
           port={port},\n  \
           password={password},\n  \
           mount={mount},\n  \
           name={name},\n  \
           description={description},\n  \
           genre={genre},\n  \
           public={public},\n  \
           encoding=\"UTF-8\",\n  \
           radio\n\
         )\n",
        host = liq_string(&out.host),
        port = out.port,
        password = liq_string(&out.password),
        mount = liq_string(&out.mount),
        name = liq_string(name),
        description = liq_string(out.description.as_deref().unwrap_or("")),
        genre = liq_string(out.genre.as_deref().unwrap_or("")),
        public = out.public,
    )
}

/// Write the script only when its content changed (atomic: temp + rename).
/// Returns `true` when the file was (re)written — Liquidsoap must then be
/// restarted to pick it up.
pub fn write_if_changed(path: &Path, script: &str) -> std::io::Result<bool> {
    if let Ok(current) = std::fs::read_to_string(path) {
        if current == script {
            return Ok(false);
        }
    }
    if let Some(dir) = path.parent().filter(|d| !d.as_os_str().is_empty()) {
        std::fs::create_dir_all(dir)?;
    }
    let tmp = path.with_extension("liq.tmp");
    std::fs::write(&tmp, script)?;
    std::fs::rename(&tmp, path)?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{CrossfadeConfig, IcecastOutput};
    use std::path::PathBuf;

    fn cfg() -> LiquidsoapConfig {
        LiquidsoapConfig {
            script_path: PathBuf::from("/tmp/x.liq"),
            http_bind: "127.0.0.1:8081".into(),
            api_token: "tok".into(),
            fallback_path: PathBuf::from("/srv/error.mp3"),
            halted_path: PathBuf::from("/srv/noise.mp3"),
            crossfade: CrossfadeConfig::default(),
            normalize: false,
            custom_include: None,
            log_level: 3,
            outputs: vec![IcecastOutput {
                host: "127.0.0.1".into(),
                port: 8000,
                password: "hack\"me".into(),
                mount: "/radio.mp3".into(),
                format: OutputFormat::Mp3,
                bitrate: 192,
                name: None,
                description: Some("Pre production radio".into()),
                genre: None,
                public: false,
            }],
        }
    }

    #[test]
    fn strings_are_escaped_and_never_interpolated() {
        assert_eq!(liq_string("plain"), "\"plain\"");
        assert_eq!(liq_string("a\"b\\c"), "\"a\\\"b\\\\c\"");
        assert_eq!(liq_string("x#{y}"), "(\"x#\" ^ \"{y}\")");
        assert_eq!(liq_string("#{a}#{b}"), "(\"#\" ^ \"{a}#\" ^ \"{b}\")");
        assert_eq!(liq_string("l1\nl2"), "\"l1\\nl2\"");
    }

    #[test]
    fn floats_always_have_a_point() {
        assert_eq!(liq_float(2.0), "2.");
        assert_eq!(liq_float(0.5), "0.5");
    }

    #[test]
    fn renders_the_bridge_chain_and_outputs() {
        let s = render(&cfg(), "Ma Radio");
        assert!(s.contains("let stationd.api_url = \"http://127.0.0.1:8081/ls/v1\""));
        assert!(s.contains("let stationd.api_token = \"tok\""));
        assert!(s.contains("request.dynamic(id=\"stationd_pull\""));
        assert!(s.contains("stationd.next_not_before := time() + 2."));
        assert!(s.contains("cross(id=\"stationd_cross\", duration=3."));
        assert!(s.contains("fade_in=2., fade_out=2."));
        assert!(s.contains("single(id=\"stationd_halted\", \"/srv/noise.mp3\")"));
        assert!(s.contains("source.methods(halted_noise).on_track(synchronous=false, fun (_) -> stationd.report(\"\", \"halted\"))"));
        assert!(s.contains("single(id=\"stationd_fallback\", \"/srv/error.mp3\")"));
        assert!(s.contains("source.methods(safety).on_track(synchronous=false, fun (_) -> stationd.report(\"\", \"fallback\"))"));
        assert!(!s.contains("\"annotate:"), "annotate: makes single() fallible");
        // pull first, halted noise before the safety fallback.
        let pull = s.find("    pull,").unwrap();
        let halted = s.find("source.available(halted_noise").unwrap();
        let safety = s.find("    safety\n").unwrap();
        assert!(pull < halted && halted < safety);
        // Track starts observed on the pull BEFORE the crossfade.
        let report = s.find("source.methods(pull).on_track(synchronous=false").unwrap();
        assert!(report < s.find("cross(id=").unwrap());
        assert!(s.contains("b=\"192k\""));
        assert!(s.contains("password=\"hack\\\"me\""));
        assert!(s.contains("name=\"Ma Radio\""));
        assert!(s.contains("description=\"Pre production radio\""));
        assert!(s.contains("public=false"));
        assert!(!s.contains("normalize("));
        assert!(!s.contains("%include"));
    }

    #[test]
    fn optional_parts() {
        let mut c = cfg();
        c.crossfade.mode = CrossfadeMode::None;
        c.normalize = true;
        c.custom_include = Some(PathBuf::from("/etc/stationd/custom.liq"));
        c.outputs.push(IcecastOutput { mount: "/low.mp3".into(), bitrate: 64, ..c.outputs[0].clone() });
        let s = render(&c, "R");
        assert!(!s.contains("cross("));
        assert!(s.contains("compress.exponential"));
        assert!(s.contains("%include \"/etc/stationd/custom.liq\""));
        // the include comes before the outputs (it may reassign `radio`).
        assert!(s.find("%include").unwrap() < s.find("output.icecast").unwrap());
        assert!(s.contains("id=\"stationd_out_2\""));
        assert!(s.contains("b=\"64k\""));
    }

    #[test]
    fn write_only_when_changed() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("sub/station.liq");
        assert!(write_if_changed(&p, "a").unwrap());
        assert!(!write_if_changed(&p, "a").unwrap());
        assert!(write_if_changed(&p, "b").unwrap());
        assert_eq!(std::fs::read_to_string(&p).unwrap(), "b");
    }
}
