//! gRPC transport for the dedicated scheduling service (schedule_v1.proto).
//!
//! Thin translator over `GridEngine`, same discipline as `grpc.rs`: no metier
//! here, just map the proto to the engine and back. Served on the same tonic
//! server as `Station` (one port, two services).
//!
//! Only `resolve_next` is live for now — the live path Liquidsoap hits at each
//! track boundary. The grid CRUD (apply/validate/export/list) and `preview`
//! return UNIMPLEMENTED until the grid TOML grammar and the grid projection
//! exist; they are declared so the contract is complete and CLI-reachable the
//! moment they are filled in.

use tonic::{Request, Response, Status};

use crate::grid_engine::GridEngine;
use crate::resolver::{Epoch, Origin};

// Code generated by tonic-build from proto/schedule_v1.proto (see build.rs).
pub mod schedule {
    tonic::include_proto!("webradio.schedule.v1");
}

use schedule::schedule_service_server::ScheduleService;
use schedule::{
    ApplyGridRequest, ApplyGridResponse, Decision, ExportGridRequest, ExportGridResponse,
    ListRulesRequest, ListRulesResponse, PreviewRequest, PreviewResponse, ResolveNextRequest,
    ValidateGridResponse,
};

pub struct ScheduleGrpc {
    engine: GridEngine,
}

impl ScheduleGrpc {
    pub fn new(engine: GridEngine) -> Self {
        Self { engine }
    }
}

fn now_epoch_seconds() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

fn map_origin(o: Origin) -> schedule::decision::Origin {
    use schedule::decision::Origin as P;
    match o {
        Origin::AtClockHard => P::AtClockHard,
        Origin::AtClockSoft => P::AtClockSoft,
        Origin::Every => P::Every,
        Origin::DayPart => P::DayPart,
        Origin::BaseRotation => P::BaseRotation,
        Origin::Fallback => P::Fallback,
    }
}

#[tonic::async_trait]
impl ScheduleService for ScheduleGrpc {
    /// The live resolver: what to pull at a track boundary. `now` absent means
    /// "now" (the Liquidsoap path); a supplied instant drives a deterministic
    /// query (the seed of `preview`, and of testing without the wall clock).
    async fn resolve_next(
        &self,
        request: Request<ResolveNextRequest>,
    ) -> Result<Response<Decision>, Status> {
        let now = match request.into_inner().now {
            Some(ts) => Epoch(ts.seconds),
            None => Epoch(now_epoch_seconds()),
        };
        let decision = self
            .engine
            .next(now)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;

        Ok(Response::new(Decision {
            // The grid resolves a source; turning a playlist_ref into a concrete
            // media file is the downstream selection stage, not wired here yet.
            media_path: String::new(),
            playlist_ref: decision.playlist_ref.unwrap_or_default(),
            rule_id: decision.rule_id.unwrap_or_default(),
            origin: map_origin(decision.origin) as i32,
        }))
    }

    async fn apply_grid(
        &self,
        _request: Request<ApplyGridRequest>,
    ) -> Result<Response<ApplyGridResponse>, Status> {
        Err(Status::unimplemented(
            "grid apply awaits the grid TOML grammar",
        ))
    }

    async fn validate_grid(
        &self,
        _request: Request<ApplyGridRequest>,
    ) -> Result<Response<ValidateGridResponse>, Status> {
        Err(Status::unimplemented(
            "grid validate awaits the grid TOML grammar",
        ))
    }

    async fn export_grid(
        &self,
        _request: Request<ExportGridRequest>,
    ) -> Result<Response<ExportGridResponse>, Status> {
        Err(Status::unimplemented(
            "grid export awaits the grid TOML grammar",
        ))
    }

    async fn list_rules(
        &self,
        _request: Request<ListRulesRequest>,
    ) -> Result<Response<ListRulesResponse>, Status> {
        Err(Status::unimplemented("list_rules not wired yet"))
    }

    async fn preview(
        &self,
        _request: Request<PreviewRequest>,
    ) -> Result<Response<PreviewResponse>, Status> {
        Err(Status::unimplemented(
            "preview is a grid projection, not yet implemented",
        ))
    }
}
